/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class HelloWorld {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String... a) {
    	System.out.println("Hello World");
    }
}
